### PR TITLE
Adjust default alignment for media object elements

### PR DESCRIPTION
**Pull request by timonkbd**
I often find myself using a `vertical-align: top` on the media object elements. So adding a modifier to the media object for this seems to be straightforward.

### CODE REVIEW

**Comment by andrewckor** [comment]
Hey @timonweber the default behaviour of the media object is to top-align its children. Is there any specific reason you want a top specific class?

```
.o-media          // Top
.o-media--middle  // Middle
.o-media--bottom  // Bottom
```

**Comment by timonkbd** [comment]
Hey @andrewckor, thanks for stopping by!

You are right, **when `$iota-objs-media-flex` is enabled,** the media object elements are aligned at the top per default. But otherwise (as the `vertical-align` attribute is not set at all) they fall back to `vertical-align: baseline`.

In terms of consistency it would be better to set `vertical-align: top` as a default for non-flexbox configurations, but I guess this would break some layouts out there…

**Comment by harby** [comment]
Hey @timonweber, sorry for not getting back to you earlier. You are right, this is a small inconsistency. I would normalize the Media to behave the same with and without flexbox ( by making sure it aligns on top by default always ) instead of adding another modifier that will not be used at all with flexbox enabled. Also, according to a small research I did, most of the people who use iotaCSS enable flexbox. What do you think? @timonweber @andrewckor

**Comment by timonkbd** [comment]
I’m totally fine with this approach and will update the PR accordingly. If most people have flexbox enabled, this change won’t affect them anyway.

As you see I run some projects which needs greater browser compatibility and therefore I’m happy that most features of iotaCSS can still be used without flexbox.

**Comment by andrewckor** [comment]
👍@timonweber
@harby do you wanna merge?

**Review by harby — APPROVED** [review]

**Pull request merged**
